blank_issues_enabled: false
contact_links:
    - name: Documentation Issue
      url: https://github.com/Synnech
      about: This issue tracker is not for documentation issues. Consider contacting us directly.
    - name: Questions and Help
      url: https://github.com/Synnech/risper/discussions
      about: This issue tracker is not for support questions. Please refer to the Risper community discussions instead.
